# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='edu.cmu.raftj.rpc',
  serialized_pb=_b('\n\x0emessages.proto\x12\x11\x65\x64u.cmu.raftj.rpc\";\n\x08LogEntry\x12\x10\n\x08logIndex\x18\x01 \x02(\x03\x12\x0c\n\x04term\x18\x02 \x02(\x03\x12\x0f\n\x07\x63ommand\x18\x03 \x02(\t\"y\n\x10PersistenceEntry\x12/\n\x08logEntry\x18\x01 \x01(\x0b\x32\x1b.edu.cmu.raftj.rpc.LogEntryH\x00\x12\x15\n\x0b\x63urrentTerm\x18\x02 \x01(\x03H\x00\x12\x12\n\x08votedFor\x18\x03 \x01(\tH\x00\x42\t\n\x07payload\"d\n\x0bVoteRequest\x12\x15\n\rcandidateTerm\x18\x01 \x02(\x03\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x02(\t\x12\x14\n\x0clastLogIndex\x18\x03 \x02(\x03\x12\x13\n\x0blastLogTerm\x18\x04 \x02(\x03\"C\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x02(\x03\x12\x13\n\x0bvoteGranted\x18\x02 \x02(\x08\x12\x10\n\x08senderID\x18\x03 \x02(\t\"\xb3\x01\n\x14\x41ppendEntriesRequest\x12\x12\n\nleaderTerm\x18\x01 \x02(\x03\x12\x10\n\x08leaderId\x18\x02 \x02(\t\x12\x14\n\x0cprevLogIndex\x18\x03 \x02(\x03\x12\x13\n\x0bprevLogTerm\x18\x04 \x02(\x03\x12/\n\nlogEntries\x18\x05 \x03(\x0b\x32\x1b.edu.cmu.raftj.rpc.LogEntry\x12\x19\n\x11leaderCommitIndex\x18\x06 \x02(\x03\"H\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x02(\x03\x12\x0f\n\x07success\x18\x02 \x02(\x08\x12\x10\n\x08senderID\x18\x03 \x02(\t\":\n\x15\x43lientMessageResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x10\n\x08leaderID\x18\x02 \x01(\t\"\xa7\x01\n\x07Request\x12\x35\n\x0bvoteRequest\x18\x01 \x01(\x0b\x32\x1e.edu.cmu.raftj.rpc.VoteRequestH\x00\x12G\n\x14\x61ppendEntriesRequest\x18\x02 \x01(\x0b\x32\'.edu.cmu.raftj.rpc.AppendEntriesRequestH\x00\x12\x11\n\x07\x63ommand\x18\x03 \x01(\tH\x00\x42\t\n\x07payload')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOGENTRY = _descriptor.Descriptor(
  name='LogEntry',
  full_name='edu.cmu.raftj.rpc.LogEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logIndex', full_name='edu.cmu.raftj.rpc.LogEntry.logIndex', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='term', full_name='edu.cmu.raftj.rpc.LogEntry.term', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command', full_name='edu.cmu.raftj.rpc.LogEntry.command', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=96,
)


_PERSISTENCEENTRY = _descriptor.Descriptor(
  name='PersistenceEntry',
  full_name='edu.cmu.raftj.rpc.PersistenceEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logEntry', full_name='edu.cmu.raftj.rpc.PersistenceEntry.logEntry', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currentTerm', full_name='edu.cmu.raftj.rpc.PersistenceEntry.currentTerm', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='votedFor', full_name='edu.cmu.raftj.rpc.PersistenceEntry.votedFor', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='edu.cmu.raftj.rpc.PersistenceEntry.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=98,
  serialized_end=219,
)


_VOTEREQUEST = _descriptor.Descriptor(
  name='VoteRequest',
  full_name='edu.cmu.raftj.rpc.VoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='candidateTerm', full_name='edu.cmu.raftj.rpc.VoteRequest.candidateTerm', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='candidateId', full_name='edu.cmu.raftj.rpc.VoteRequest.candidateId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastLogIndex', full_name='edu.cmu.raftj.rpc.VoteRequest.lastLogIndex', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastLogTerm', full_name='edu.cmu.raftj.rpc.VoteRequest.lastLogTerm', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=321,
)


_VOTERESPONSE = _descriptor.Descriptor(
  name='VoteResponse',
  full_name='edu.cmu.raftj.rpc.VoteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='edu.cmu.raftj.rpc.VoteResponse.term', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voteGranted', full_name='edu.cmu.raftj.rpc.VoteResponse.voteGranted', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='senderID', full_name='edu.cmu.raftj.rpc.VoteResponse.senderID', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=390,
)


_APPENDENTRIESREQUEST = _descriptor.Descriptor(
  name='AppendEntriesRequest',
  full_name='edu.cmu.raftj.rpc.AppendEntriesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leaderTerm', full_name='edu.cmu.raftj.rpc.AppendEntriesRequest.leaderTerm', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leaderId', full_name='edu.cmu.raftj.rpc.AppendEntriesRequest.leaderId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prevLogIndex', full_name='edu.cmu.raftj.rpc.AppendEntriesRequest.prevLogIndex', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prevLogTerm', full_name='edu.cmu.raftj.rpc.AppendEntriesRequest.prevLogTerm', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logEntries', full_name='edu.cmu.raftj.rpc.AppendEntriesRequest.logEntries', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leaderCommitIndex', full_name='edu.cmu.raftj.rpc.AppendEntriesRequest.leaderCommitIndex', index=5,
      number=6, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=572,
)


_APPENDENTRIESRESPONSE = _descriptor.Descriptor(
  name='AppendEntriesResponse',
  full_name='edu.cmu.raftj.rpc.AppendEntriesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='edu.cmu.raftj.rpc.AppendEntriesResponse.term', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='edu.cmu.raftj.rpc.AppendEntriesResponse.success', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='senderID', full_name='edu.cmu.raftj.rpc.AppendEntriesResponse.senderID', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=646,
)


_CLIENTMESSAGERESPONSE = _descriptor.Descriptor(
  name='ClientMessageResponse',
  full_name='edu.cmu.raftj.rpc.ClientMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='edu.cmu.raftj.rpc.ClientMessageResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leaderID', full_name='edu.cmu.raftj.rpc.ClientMessageResponse.leaderID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=648,
  serialized_end=706,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='edu.cmu.raftj.rpc.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='voteRequest', full_name='edu.cmu.raftj.rpc.Request.voteRequest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appendEntriesRequest', full_name='edu.cmu.raftj.rpc.Request.appendEntriesRequest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command', full_name='edu.cmu.raftj.rpc.Request.command', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='edu.cmu.raftj.rpc.Request.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=709,
  serialized_end=876,
)

_PERSISTENCEENTRY.fields_by_name['logEntry'].message_type = _LOGENTRY
_PERSISTENCEENTRY.oneofs_by_name['payload'].fields.append(
  _PERSISTENCEENTRY.fields_by_name['logEntry'])
_PERSISTENCEENTRY.fields_by_name['logEntry'].containing_oneof = _PERSISTENCEENTRY.oneofs_by_name['payload']
_PERSISTENCEENTRY.oneofs_by_name['payload'].fields.append(
  _PERSISTENCEENTRY.fields_by_name['currentTerm'])
_PERSISTENCEENTRY.fields_by_name['currentTerm'].containing_oneof = _PERSISTENCEENTRY.oneofs_by_name['payload']
_PERSISTENCEENTRY.oneofs_by_name['payload'].fields.append(
  _PERSISTENCEENTRY.fields_by_name['votedFor'])
_PERSISTENCEENTRY.fields_by_name['votedFor'].containing_oneof = _PERSISTENCEENTRY.oneofs_by_name['payload']
_APPENDENTRIESREQUEST.fields_by_name['logEntries'].message_type = _LOGENTRY
_REQUEST.fields_by_name['voteRequest'].message_type = _VOTEREQUEST
_REQUEST.fields_by_name['appendEntriesRequest'].message_type = _APPENDENTRIESREQUEST
_REQUEST.oneofs_by_name['payload'].fields.append(
  _REQUEST.fields_by_name['voteRequest'])
_REQUEST.fields_by_name['voteRequest'].containing_oneof = _REQUEST.oneofs_by_name['payload']
_REQUEST.oneofs_by_name['payload'].fields.append(
  _REQUEST.fields_by_name['appendEntriesRequest'])
_REQUEST.fields_by_name['appendEntriesRequest'].containing_oneof = _REQUEST.oneofs_by_name['payload']
_REQUEST.oneofs_by_name['payload'].fields.append(
  _REQUEST.fields_by_name['command'])
_REQUEST.fields_by_name['command'].containing_oneof = _REQUEST.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['LogEntry'] = _LOGENTRY
DESCRIPTOR.message_types_by_name['PersistenceEntry'] = _PERSISTENCEENTRY
DESCRIPTOR.message_types_by_name['VoteRequest'] = _VOTEREQUEST
DESCRIPTOR.message_types_by_name['VoteResponse'] = _VOTERESPONSE
DESCRIPTOR.message_types_by_name['AppendEntriesRequest'] = _APPENDENTRIESREQUEST
DESCRIPTOR.message_types_by_name['AppendEntriesResponse'] = _APPENDENTRIESRESPONSE
DESCRIPTOR.message_types_by_name['ClientMessageResponse'] = _CLIENTMESSAGERESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST

LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), dict(
  DESCRIPTOR = _LOGENTRY,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:edu.cmu.raftj.rpc.LogEntry)
  ))
_sym_db.RegisterMessage(LogEntry)

PersistenceEntry = _reflection.GeneratedProtocolMessageType('PersistenceEntry', (_message.Message,), dict(
  DESCRIPTOR = _PERSISTENCEENTRY,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:edu.cmu.raftj.rpc.PersistenceEntry)
  ))
_sym_db.RegisterMessage(PersistenceEntry)

VoteRequest = _reflection.GeneratedProtocolMessageType('VoteRequest', (_message.Message,), dict(
  DESCRIPTOR = _VOTEREQUEST,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:edu.cmu.raftj.rpc.VoteRequest)
  ))
_sym_db.RegisterMessage(VoteRequest)

VoteResponse = _reflection.GeneratedProtocolMessageType('VoteResponse', (_message.Message,), dict(
  DESCRIPTOR = _VOTERESPONSE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:edu.cmu.raftj.rpc.VoteResponse)
  ))
_sym_db.RegisterMessage(VoteResponse)

AppendEntriesRequest = _reflection.GeneratedProtocolMessageType('AppendEntriesRequest', (_message.Message,), dict(
  DESCRIPTOR = _APPENDENTRIESREQUEST,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:edu.cmu.raftj.rpc.AppendEntriesRequest)
  ))
_sym_db.RegisterMessage(AppendEntriesRequest)

AppendEntriesResponse = _reflection.GeneratedProtocolMessageType('AppendEntriesResponse', (_message.Message,), dict(
  DESCRIPTOR = _APPENDENTRIESRESPONSE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:edu.cmu.raftj.rpc.AppendEntriesResponse)
  ))
_sym_db.RegisterMessage(AppendEntriesResponse)

ClientMessageResponse = _reflection.GeneratedProtocolMessageType('ClientMessageResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTMESSAGERESPONSE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:edu.cmu.raftj.rpc.ClientMessageResponse)
  ))
_sym_db.RegisterMessage(ClientMessageResponse)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:edu.cmu.raftj.rpc.Request)
  ))
_sym_db.RegisterMessage(Request)


# @@protoc_insertion_point(module_scope)
